services:
  - type: web
    name: n8n
    env: docker
    plan: starter   # Podés elegir free, starter o pro según tu cuenta
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_HOST
        value: "n8n.onrender.com"  # Cambiar al dominio que Render te dé
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: "https://n8n.onrender.com/"
